# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 250))
        MainWindow.setMaximumSize(QtCore.QSize(600, 350))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lbTemplate = QtWidgets.QLabel(self.centralwidget)
        self.lbTemplate.setObjectName("lbTemplate")
        self.horizontalLayout_3.addWidget(self.lbTemplate)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btTemplate = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btTemplate.sizePolicy().hasHeightForWidth())
        self.btTemplate.setSizePolicy(sizePolicy)
        self.btTemplate.setMinimumSize(QtCore.QSize(30, 0))
        self.btTemplate.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btTemplate.setObjectName("btTemplate")
        self.horizontalLayout_3.addWidget(self.btTemplate)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lbScanFolder = QtWidgets.QLabel(self.centralwidget)
        self.lbScanFolder.setObjectName("lbScanFolder")
        self.horizontalLayout.addWidget(self.lbScanFolder)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btScanFolder = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btScanFolder.sizePolicy().hasHeightForWidth())
        self.btScanFolder.setSizePolicy(sizePolicy)
        self.btScanFolder.setMinimumSize(QtCore.QSize(30, 0))
        self.btScanFolder.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btScanFolder.setObjectName("btScanFolder")
        self.horizontalLayout.addWidget(self.btScanFolder)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lbDestFolder = QtWidgets.QLabel(self.centralwidget)
        self.lbDestFolder.setObjectName("lbDestFolder")
        self.horizontalLayout_2.addWidget(self.lbDestFolder)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btDestFolder = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btDestFolder.sizePolicy().hasHeightForWidth())
        self.btDestFolder.setSizePolicy(sizePolicy)
        self.btDestFolder.setMinimumSize(QtCore.QSize(30, 0))
        self.btDestFolder.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btDestFolder.setObjectName("btDestFolder")
        self.horizontalLayout_2.addWidget(self.btDestFolder)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(23, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.chbAutoOpen = QtWidgets.QCheckBox(self.centralwidget)
        self.chbAutoOpen.setObjectName("chbAutoOpen")
        self.verticalLayout.addWidget(self.chbAutoOpen)
        self.chbDeleteXML = QtWidgets.QCheckBox(self.centralwidget)
        self.chbDeleteXML.setObjectName("chbDeleteXML")
        self.verticalLayout.addWidget(self.chbDeleteXML)
        self.chbCalibration = QtWidgets.QCheckBox(self.centralwidget)
        self.chbCalibration.setObjectName("chbCalibration")
        self.verticalLayout.addWidget(self.chbCalibration)
        self.chbApproval = QtWidgets.QCheckBox(self.centralwidget)
        self.chbApproval.setObjectName("chbApproval")
        self.verticalLayout.addWidget(self.chbApproval)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.CSM = QtWidgets.QLineEdit(self.centralwidget)
        self.CSM.setObjectName("CSM")
        self.horizontalLayout_4.addWidget(self.CSM)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.exitAction = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitAction.setIcon(icon1)
        self.exitAction.setObjectName("exitAction")
        self.startAction = QtWidgets.QAction(MainWindow)
        self.startAction.setCheckable(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/player_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startAction.setIcon(icon2)
        self.startAction.setObjectName("startAction")
        self.stopAction = QtWidgets.QAction(MainWindow)
        self.stopAction.setCheckable(False)
        self.stopAction.setEnabled(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/player_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopAction.setIcon(icon3)
        self.stopAction.setVisible(True)
        self.stopAction.setIconVisibleInMenu(False)
        self.stopAction.setObjectName("stopAction")
        self.toolBar.addAction(self.exitAction)
        self.toolBar.addAction(self.startAction)
        self.toolBar.addAction(self.stopAction)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Шаблон поверки гирь:"))
        self.lbTemplate.setText(_translate("MainWindow", "C:\\шаблон.xls"))
        self.btTemplate.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplate.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplate.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Папка XML:"))
        self.lbScanFolder.setText(_translate("MainWindow", "C:\\XML"))
        self.btScanFolder.setToolTip(_translate("MainWindow", "Кнопка изменения папки XML"))
        self.btScanFolder.setStatusTip(_translate("MainWindow", "Кнопка изменения папки XML"))
        self.btScanFolder.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Папка Excel:"))
        self.lbDestFolder.setText(_translate("MainWindow", "C:\\Excel"))
        self.btDestFolder.setToolTip(_translate("MainWindow", "Кнопка изменения папки Excel"))
        self.btDestFolder.setStatusTip(_translate("MainWindow", "Кнопка изменения папки Excel"))
        self.btDestFolder.setText(_translate("MainWindow", "..."))
        self.chbAutoOpen.setToolTip(_translate("MainWindow", "Автооткрытие протокола"))
        self.chbAutoOpen.setStatusTip(_translate("MainWindow", "Автооткрытие протокола"))
        self.chbAutoOpen.setText(_translate("MainWindow", "Автооткрытие"))
        self.chbDeleteXML.setText(_translate("MainWindow", "Удаление XML"))
        self.chbCalibration.setText(_translate("MainWindow", "Калибровка"))
        self.chbApproval.setText(_translate("MainWindow", "Поверка компаратора"))
        self.label_7.setText(_translate("MainWindow", "Предприятие"))
        self.CSM.setText(_translate("MainWindow", "Красноярский ЦСМ"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.exitAction.setText(_translate("MainWindow", "Выход"))
        self.exitAction.setStatusTip(_translate("MainWindow", "Выход"))
        self.startAction.setText(_translate("MainWindow", "Запуск автосохранения"))
        self.startAction.setStatusTip(_translate("MainWindow", "Запуск автосохранения"))
        self.stopAction.setText(_translate("MainWindow", "Остановка автосохранения"))
        self.stopAction.setStatusTip(_translate("MainWindow", "Остановка автосохранения"))

