# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(766, 546)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 300))
        MainWindow.setMaximumSize(QtCore.QSize(800, 800))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lbScanFolder = QtWidgets.QLabel(self.centralwidget)
        self.lbScanFolder.setObjectName("lbScanFolder")
        self.horizontalLayout.addWidget(self.lbScanFolder)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btScanFolder = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btScanFolder.sizePolicy().hasHeightForWidth())
        self.btScanFolder.setSizePolicy(sizePolicy)
        self.btScanFolder.setMinimumSize(QtCore.QSize(30, 0))
        self.btScanFolder.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btScanFolder.setObjectName("btScanFolder")
        self.horizontalLayout.addWidget(self.btScanFolder)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.edPLCalReportNum = QtWidgets.QLineEdit(self.centralwidget)
        self.edPLCalReportNum.setObjectName("edPLCalReportNum")
        self.gridLayout.addWidget(self.edPLCalReportNum, 18, 1, 1, 1)
        self.btSaveSettings = QtWidgets.QPushButton(self.centralwidget)
        self.btSaveSettings.setObjectName("btSaveSettings")
        self.gridLayout.addWidget(self.btSaveSettings, 0, 1, 1, 1)
        self.edCalCertNum = QtWidgets.QLineEdit(self.centralwidget)
        self.edCalCertNum.setObjectName("edCalCertNum")
        self.gridLayout.addWidget(self.edCalCertNum, 8, 1, 1, 1)
        self.edTemplateReserved = QtWidgets.QLineEdit(self.centralwidget)
        self.edTemplateReserved.setEnabled(True)
        self.edTemplateReserved.setObjectName("edTemplateReserved")
        self.gridLayout.addWidget(self.edTemplateReserved, 20, 1, 1, 1)
        self.edApprovalReportNum = QtWidgets.QLineEdit(self.centralwidget)
        self.edApprovalReportNum.setObjectName("edApprovalReportNum")
        self.gridLayout.addWidget(self.edApprovalReportNum, 4, 1, 1, 1)
        self.edErrorNum = QtWidgets.QLineEdit(self.centralwidget)
        self.edErrorNum.setObjectName("edErrorNum")
        self.gridLayout.addWidget(self.edErrorNum, 6, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cbxCalCert = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxCalCert.setObjectName("cbxCalCert")
        self.horizontalLayout_9.addWidget(self.cbxCalCert)
        self.lbTemplateCalCert = QtWidgets.QLabel(self.centralwidget)
        self.lbTemplateCalCert.setObjectName("lbTemplateCalCert")
        self.horizontalLayout_9.addWidget(self.lbTemplateCalCert)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.btTemplateCalCert = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btTemplateCalCert.sizePolicy().hasHeightForWidth())
        self.btTemplateCalCert.setSizePolicy(sizePolicy)
        self.btTemplateCalCert.setMinimumSize(QtCore.QSize(30, 0))
        self.btTemplateCalCert.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btTemplateCalCert.setObjectName("btTemplateCalCert")
        self.horizontalLayout_9.addWidget(self.btTemplateCalCert)
        self.gridLayout.addLayout(self.horizontalLayout_9, 8, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbxApprovalReport = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxApprovalReport.setObjectName("cbxApprovalReport")
        self.horizontalLayout_3.addWidget(self.cbxApprovalReport)
        self.lbTemplateApprovalReport = QtWidgets.QLabel(self.centralwidget)
        self.lbTemplateApprovalReport.setObjectName("lbTemplateApprovalReport")
        self.horizontalLayout_3.addWidget(self.lbTemplateApprovalReport)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btTemplateApprovalReport = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btTemplateApprovalReport.sizePolicy().hasHeightForWidth())
        self.btTemplateApprovalReport.setSizePolicy(sizePolicy)
        self.btTemplateApprovalReport.setMinimumSize(QtCore.QSize(30, 0))
        self.btTemplateApprovalReport.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btTemplateApprovalReport.setObjectName("btTemplateApprovalReport")
        self.horizontalLayout_3.addWidget(self.btTemplateApprovalReport)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.hlPLCalReport = QtWidgets.QHBoxLayout()
        self.hlPLCalReport.setObjectName("hlPLCalReport")
        self.cbxPLCalReport = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxPLCalReport.setObjectName("cbxPLCalReport")
        self.hlPLCalReport.addWidget(self.cbxPLCalReport)
        self.lbPLTemplateCalReport = QtWidgets.QLabel(self.centralwidget)
        self.lbPLTemplateCalReport.setObjectName("lbPLTemplateCalReport")
        self.hlPLCalReport.addWidget(self.lbPLTemplateCalReport)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlPLCalReport.addItem(spacerItem3)
        self.btPLTemplateCalReport = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btPLTemplateCalReport.sizePolicy().hasHeightForWidth())
        self.btPLTemplateCalReport.setSizePolicy(sizePolicy)
        self.btPLTemplateCalReport.setMinimumSize(QtCore.QSize(30, 0))
        self.btPLTemplateCalReport.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btPLTemplateCalReport.setObjectName("btPLTemplateCalReport")
        self.hlPLCalReport.addWidget(self.btPLTemplateCalReport)
        self.gridLayout.addLayout(self.hlPLCalReport, 18, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout.addLayout(self.horizontalLayout_10, 20, 0, 1, 1)
        self.edPLErrorNum = QtWidgets.QLineEdit(self.centralwidget)
        self.edPLErrorNum.setObjectName("edPLErrorNum")
        self.gridLayout.addWidget(self.edPLErrorNum, 17, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 0, 1, 1)
        self.hlDestFolder = QtWidgets.QHBoxLayout()
        self.hlDestFolder.setObjectName("hlDestFolder")
        self.lbNameDestFolder = QtWidgets.QLabel(self.centralwidget)
        self.lbNameDestFolder.setObjectName("lbNameDestFolder")
        self.hlDestFolder.addWidget(self.lbNameDestFolder)
        self.lbDestFolder = QtWidgets.QLabel(self.centralwidget)
        self.lbDestFolder.setObjectName("lbDestFolder")
        self.hlDestFolder.addWidget(self.lbDestFolder)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlDestFolder.addItem(spacerItem4)
        self.btDestFolder = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btDestFolder.sizePolicy().hasHeightForWidth())
        self.btDestFolder.setSizePolicy(sizePolicy)
        self.btDestFolder.setMinimumSize(QtCore.QSize(30, 0))
        self.btDestFolder.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btDestFolder.setObjectName("btDestFolder")
        self.hlDestFolder.addWidget(self.btDestFolder)
        self.gridLayout.addLayout(self.hlDestFolder, 2, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lbPaths = QtWidgets.QLabel(self.centralwidget)
        self.lbPaths.setAlignment(QtCore.Qt.AlignCenter)
        self.lbPaths.setObjectName("lbPaths")
        self.horizontalLayout_12.addWidget(self.lbPaths)
        self.gridLayout.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.edPLApprovalCertNum = QtWidgets.QLineEdit(self.centralwidget)
        self.edPLApprovalCertNum.setObjectName("edPLApprovalCertNum")
        self.gridLayout.addWidget(self.edPLApprovalCertNum, 16, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout_11, 3, 0, 1, 1)
        self.edCalReportNum = QtWidgets.QLineEdit(self.centralwidget)
        self.edCalReportNum.setObjectName("edCalReportNum")
        self.gridLayout.addWidget(self.edCalReportNum, 7, 1, 1, 1)
        self.hlPLApprovalCert = QtWidgets.QHBoxLayout()
        self.hlPLApprovalCert.setObjectName("hlPLApprovalCert")
        self.cbxPLApprovalCert = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxPLApprovalCert.setObjectName("cbxPLApprovalCert")
        self.hlPLApprovalCert.addWidget(self.cbxPLApprovalCert)
        self.lbPLTemplateApprovalCert = QtWidgets.QLabel(self.centralwidget)
        self.lbPLTemplateApprovalCert.setObjectName("lbPLTemplateApprovalCert")
        self.hlPLApprovalCert.addWidget(self.lbPLTemplateApprovalCert)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlPLApprovalCert.addItem(spacerItem5)
        self.btPLTemplateApprovalCert = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btPLTemplateApprovalCert.sizePolicy().hasHeightForWidth())
        self.btPLTemplateApprovalCert.setSizePolicy(sizePolicy)
        self.btPLTemplateApprovalCert.setMinimumSize(QtCore.QSize(30, 0))
        self.btPLTemplateApprovalCert.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btPLTemplateApprovalCert.setObjectName("btPLTemplateApprovalCert")
        self.hlPLApprovalCert.addWidget(self.btPLTemplateApprovalCert)
        self.gridLayout.addLayout(self.hlPLApprovalCert, 16, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cbxError = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxError.setObjectName("cbxError")
        self.horizontalLayout_7.addWidget(self.cbxError)
        self.lbTemplateError = QtWidgets.QLabel(self.centralwidget)
        self.lbTemplateError.setObjectName("lbTemplateError")
        self.horizontalLayout_7.addWidget(self.lbTemplateError)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.btTemplateError = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btTemplateError.sizePolicy().hasHeightForWidth())
        self.btTemplateError.setSizePolicy(sizePolicy)
        self.btTemplateError.setMinimumSize(QtCore.QSize(30, 0))
        self.btTemplateError.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btTemplateError.setObjectName("btTemplateError")
        self.horizontalLayout_7.addWidget(self.btTemplateError)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.hlTemplateApprovalCert = QtWidgets.QHBoxLayout()
        self.hlTemplateApprovalCert.setObjectName("hlTemplateApprovalCert")
        self.cbxApprovalCert = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxApprovalCert.setObjectName("cbxApprovalCert")
        self.hlTemplateApprovalCert.addWidget(self.cbxApprovalCert)
        self.lbTemplateApprovalCert = QtWidgets.QLabel(self.centralwidget)
        self.lbTemplateApprovalCert.setObjectName("lbTemplateApprovalCert")
        self.hlTemplateApprovalCert.addWidget(self.lbTemplateApprovalCert)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlTemplateApprovalCert.addItem(spacerItem7)
        self.btTemplateApprovalCert = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btTemplateApprovalCert.sizePolicy().hasHeightForWidth())
        self.btTemplateApprovalCert.setSizePolicy(sizePolicy)
        self.btTemplateApprovalCert.setMinimumSize(QtCore.QSize(30, 0))
        self.btTemplateApprovalCert.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btTemplateApprovalCert.setObjectName("btTemplateApprovalCert")
        self.hlTemplateApprovalCert.addWidget(self.btTemplateApprovalCert)
        self.gridLayout.addLayout(self.hlTemplateApprovalCert, 5, 0, 1, 1)
        self.hlbtTemplateCalReport = QtWidgets.QHBoxLayout()
        self.hlbtTemplateCalReport.setObjectName("hlbtTemplateCalReport")
        self.cbxCalReport = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxCalReport.setObjectName("cbxCalReport")
        self.hlbtTemplateCalReport.addWidget(self.cbxCalReport)
        self.lbTemplateCalReport = QtWidgets.QLabel(self.centralwidget)
        self.lbTemplateCalReport.setObjectName("lbTemplateCalReport")
        self.hlbtTemplateCalReport.addWidget(self.lbTemplateCalReport)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlbtTemplateCalReport.addItem(spacerItem8)
        self.btTemplateCalReport = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btTemplateCalReport.sizePolicy().hasHeightForWidth())
        self.btTemplateCalReport.setSizePolicy(sizePolicy)
        self.btTemplateCalReport.setMinimumSize(QtCore.QSize(30, 0))
        self.btTemplateCalReport.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btTemplateCalReport.setObjectName("btTemplateCalReport")
        self.hlbtTemplateCalReport.addWidget(self.btTemplateCalReport)
        self.gridLayout.addLayout(self.hlbtTemplateCalReport, 7, 0, 1, 1)
        self.hlPLError = QtWidgets.QHBoxLayout()
        self.hlPLError.setObjectName("hlPLError")
        self.cbxPLError = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxPLError.setObjectName("cbxPLError")
        self.hlPLError.addWidget(self.cbxPLError)
        self.lbPLTemplateError = QtWidgets.QLabel(self.centralwidget)
        self.lbPLTemplateError.setObjectName("lbPLTemplateError")
        self.hlPLError.addWidget(self.lbPLTemplateError)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlPLError.addItem(spacerItem9)
        self.btPLTemplateError = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btPLTemplateError.sizePolicy().hasHeightForWidth())
        self.btPLTemplateError.setSizePolicy(sizePolicy)
        self.btPLTemplateError.setMinimumSize(QtCore.QSize(30, 0))
        self.btPLTemplateError.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btPLTemplateError.setObjectName("btPLTemplateError")
        self.hlPLError.addWidget(self.btPLTemplateError)
        self.gridLayout.addLayout(self.hlPLError, 17, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 2, 1, 1, 1)
        self.edPLCalCertNum = QtWidgets.QLineEdit(self.centralwidget)
        self.edPLCalCertNum.setObjectName("edPLCalCertNum")
        self.gridLayout.addWidget(self.edPLCalCertNum, 19, 1, 1, 1)
        self.edApprovalCertNum = QtWidgets.QLineEdit(self.centralwidget)
        self.edApprovalCertNum.setObjectName("edApprovalCertNum")
        self.gridLayout.addWidget(self.edApprovalCertNum, 5, 1, 1, 1)
        self.hlPLCalCert = QtWidgets.QHBoxLayout()
        self.hlPLCalCert.setObjectName("hlPLCalCert")
        self.cbxPLCalCert = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxPLCalCert.setObjectName("cbxPLCalCert")
        self.hlPLCalCert.addWidget(self.cbxPLCalCert)
        self.lbPLTemplateCalCert = QtWidgets.QLabel(self.centralwidget)
        self.lbPLTemplateCalCert.setObjectName("lbPLTemplateCalCert")
        self.hlPLCalCert.addWidget(self.lbPLTemplateCalCert)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlPLCalCert.addItem(spacerItem11)
        self.btPLTemplateCalCert = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btPLTemplateCalCert.sizePolicy().hasHeightForWidth())
        self.btPLTemplateCalCert.setSizePolicy(sizePolicy)
        self.btPLTemplateCalCert.setMinimumSize(QtCore.QSize(30, 0))
        self.btPLTemplateCalCert.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btPLTemplateCalCert.setObjectName("btPLTemplateCalCert")
        self.hlPLCalCert.addWidget(self.btPLTemplateCalCert)
        self.gridLayout.addLayout(self.hlPLCalCert, 19, 0, 1, 1)
        self.hlPLApprovalReport = QtWidgets.QHBoxLayout()
        self.hlPLApprovalReport.setObjectName("hlPLApprovalReport")
        self.cbxPLApprovalReport = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxPLApprovalReport.setObjectName("cbxPLApprovalReport")
        self.hlPLApprovalReport.addWidget(self.cbxPLApprovalReport)
        self.lbPLTemplateApprovalReport = QtWidgets.QLabel(self.centralwidget)
        self.lbPLTemplateApprovalReport.setObjectName("lbPLTemplateApprovalReport")
        self.hlPLApprovalReport.addWidget(self.lbPLTemplateApprovalReport)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlPLApprovalReport.addItem(spacerItem12)
        self.btPLTemplateApprovalReport = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btPLTemplateApprovalReport.sizePolicy().hasHeightForWidth())
        self.btPLTemplateApprovalReport.setSizePolicy(sizePolicy)
        self.btPLTemplateApprovalReport.setMinimumSize(QtCore.QSize(30, 0))
        self.btPLTemplateApprovalReport.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btPLTemplateApprovalReport.setObjectName("btPLTemplateApprovalReport")
        self.hlPLApprovalReport.addWidget(self.btPLTemplateApprovalReport)
        self.gridLayout.addLayout(self.hlPLApprovalReport, 13, 0, 1, 1)
        self.hlPLApprovalReportTable = QtWidgets.QHBoxLayout()
        self.hlPLApprovalReportTable.setObjectName("hlPLApprovalReportTable")
        self.cbxPLApprovalReportTable = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxPLApprovalReportTable.setObjectName("cbxPLApprovalReportTable")
        self.hlPLApprovalReportTable.addWidget(self.cbxPLApprovalReportTable)
        self.lbPLTemplateApprovalReportTable = QtWidgets.QLabel(self.centralwidget)
        self.lbPLTemplateApprovalReportTable.setObjectName("lbPLTemplateApprovalReportTable")
        self.hlPLApprovalReportTable.addWidget(self.lbPLTemplateApprovalReportTable)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlPLApprovalReportTable.addItem(spacerItem13)
        self.btPLTemplateApprovalReportTable = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btPLTemplateApprovalReportTable.sizePolicy().hasHeightForWidth())
        self.btPLTemplateApprovalReportTable.setSizePolicy(sizePolicy)
        self.btPLTemplateApprovalReportTable.setMinimumSize(QtCore.QSize(30, 0))
        self.btPLTemplateApprovalReportTable.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btPLTemplateApprovalReportTable.setObjectName("btPLTemplateApprovalReportTable")
        self.hlPLApprovalReportTable.addWidget(self.btPLTemplateApprovalReportTable)
        self.gridLayout.addLayout(self.hlPLApprovalReportTable, 14, 0, 1, 1)
        self.edPLApprovalReportNum = QtWidgets.QLineEdit(self.centralwidget)
        self.edPLApprovalReportNum.setObjectName("edPLApprovalReportNum")
        self.gridLayout.addWidget(self.edPLApprovalReportNum, 13, 1, 1, 1)
        self.edPLApprovalReportlNumTable = QtWidgets.QLineEdit(self.centralwidget)
        self.edPLApprovalReportlNumTable.setObjectName("edPLApprovalReportlNumTable")
        self.gridLayout.addWidget(self.edPLApprovalReportlNumTable, 14, 1, 1, 1)
        self.gridLayout.setRowMinimumHeight(0, 6)
        self.gridLayout.setRowMinimumHeight(1, 6)
        self.gridLayout.setRowMinimumHeight(2, 6)
        self.gridLayout.setRowMinimumHeight(3, 6)
        self.gridLayout.setRowMinimumHeight(4, 6)
        self.gridLayout.setRowMinimumHeight(5, 6)
        self.gridLayout.setRowMinimumHeight(6, 6)
        self.gridLayout.setRowMinimumHeight(7, 6)
        self.gridLayout.setRowMinimumHeight(8, 6)
        self.gridLayout.setRowMinimumHeight(9, 6)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.chbAutoOpen = QtWidgets.QCheckBox(self.centralwidget)
        self.chbAutoOpen.setObjectName("chbAutoOpen")
        self.verticalLayout.addWidget(self.chbAutoOpen)
        self.chbAutoDelXML = QtWidgets.QCheckBox(self.centralwidget)
        self.chbAutoDelXML.setObjectName("chbAutoDelXML")
        self.verticalLayout.addWidget(self.chbAutoDelXML)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.exitAction = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitAction.setIcon(icon1)
        self.exitAction.setObjectName("exitAction")
        self.startAction = QtWidgets.QAction(MainWindow)
        self.startAction.setCheckable(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/player_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startAction.setIcon(icon2)
        self.startAction.setObjectName("startAction")
        self.stopAction = QtWidgets.QAction(MainWindow)
        self.stopAction.setCheckable(False)
        self.stopAction.setEnabled(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/player_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopAction.setIcon(icon3)
        self.stopAction.setVisible(True)
        self.stopAction.setIconVisibleInMenu(False)
        self.stopAction.setObjectName("stopAction")
        self.toolBar.addAction(self.exitAction)
        self.toolBar.addAction(self.startAction)
        self.toolBar.addAction(self.stopAction)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Папка XML:"))
        self.lbScanFolder.setText(_translate("MainWindow", "C:\\MCLinkReport\\XML"))
        self.btScanFolder.setToolTip(_translate("MainWindow", "Кнопка изменения папки XML"))
        self.btScanFolder.setStatusTip(_translate("MainWindow", "Кнопка изменения папки XML"))
        self.btScanFolder.setText(_translate("MainWindow", "..."))
        self.btSaveSettings.setText(_translate("MainWindow", "Сохранить настройки"))
        self.cbxCalCert.setText(_translate("MainWindow", "Сертификат калибровки"))
        self.lbTemplateCalCert.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btTemplateCalCert.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateCalCert.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateCalCert.setText(_translate("MainWindow", "..."))
        self.cbxApprovalReport.setText(_translate("MainWindow", "Протокол поверки"))
        self.lbTemplateApprovalReport.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btTemplateApprovalReport.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateApprovalReport.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateApprovalReport.setText(_translate("MainWindow", "..."))
        self.cbxPLCalReport.setText(_translate("MainWindow", "Протокол калибровки"))
        self.lbPLTemplateCalReport.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btPLTemplateCalReport.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btPLTemplateCalReport.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btPLTemplateCalReport.setText(_translate("MainWindow", "..."))
        self.label_10.setText(_translate("MainWindow", "Номера документов:"))
        self.label_5.setText(_translate("MainWindow", "Шаблоны документов Pipette Link:"))
        self.lbNameDestFolder.setText(_translate("MainWindow", "Папка протоколов:"))
        self.lbDestFolder.setText(_translate("MainWindow", "C:\\MCLinkReport\\Excel"))
        self.btDestFolder.setToolTip(_translate("MainWindow", "Кнопка изменения папки Excel"))
        self.btDestFolder.setStatusTip(_translate("MainWindow", "Кнопка изменения папки Excel"))
        self.btDestFolder.setText(_translate("MainWindow", "..."))
        self.lbPaths.setText(_translate("MainWindow", "Пути:"))
        self.label_2.setText(_translate("MainWindow", "Шаблоны документов MCLink:"))
        self.cbxPLApprovalCert.setText(_translate("MainWindow", "Свидетельство о поверке"))
        self.lbPLTemplateApprovalCert.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btPLTemplateApprovalCert.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btPLTemplateApprovalCert.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btPLTemplateApprovalCert.setText(_translate("MainWindow", "..."))
        self.cbxError.setText(_translate("MainWindow", "Извещение о непригодности"))
        self.lbTemplateError.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btTemplateError.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateError.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateError.setText(_translate("MainWindow", "..."))
        self.cbxApprovalCert.setText(_translate("MainWindow", "Свидетельство о поверке"))
        self.lbTemplateApprovalCert.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btTemplateApprovalCert.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateApprovalCert.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateApprovalCert.setText(_translate("MainWindow", "..."))
        self.cbxCalReport.setText(_translate("MainWindow", "Протокол калибровки"))
        self.lbTemplateCalReport.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btTemplateCalReport.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateCalReport.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateCalReport.setText(_translate("MainWindow", "..."))
        self.cbxPLError.setText(_translate("MainWindow", "Извещение о непригодности"))
        self.lbPLTemplateError.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btPLTemplateError.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btPLTemplateError.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btPLTemplateError.setText(_translate("MainWindow", "..."))
        self.cbxPLCalCert.setText(_translate("MainWindow", "Сертификат калибровки"))
        self.lbPLTemplateCalCert.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btPLTemplateCalCert.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btPLTemplateCalCert.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btPLTemplateCalCert.setText(_translate("MainWindow", "..."))
        self.cbxPLApprovalReport.setText(_translate("MainWindow", "Протокол поверки"))
        self.lbPLTemplateApprovalReport.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btPLTemplateApprovalReport.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btPLTemplateApprovalReport.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btPLTemplateApprovalReport.setText(_translate("MainWindow", "..."))
        self.cbxPLApprovalReportTable.setText(_translate("MainWindow", "Таблица протокола поверки"))
        self.lbPLTemplateApprovalReportTable.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btPLTemplateApprovalReportTable.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btPLTemplateApprovalReportTable.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btPLTemplateApprovalReportTable.setText(_translate("MainWindow", "..."))
        self.chbAutoOpen.setToolTip(_translate("MainWindow", "Автооткрытие протокола"))
        self.chbAutoOpen.setStatusTip(_translate("MainWindow", "Автооткрытие протокола"))
        self.chbAutoOpen.setText(_translate("MainWindow", "Автоматическое открытие протоколов"))
        self.chbAutoDelXML.setText(_translate("MainWindow", "Автоудаление XML"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.exitAction.setText(_translate("MainWindow", "Выход"))
        self.exitAction.setStatusTip(_translate("MainWindow", "Выход"))
        self.startAction.setText(_translate("MainWindow", "Запуск автосохранения"))
        self.startAction.setStatusTip(_translate("MainWindow", "Запуск автосохранения"))
        self.stopAction.setText(_translate("MainWindow", "Остановка автосохранения"))
        self.stopAction.setStatusTip(_translate("MainWindow", "Остановка автосохранения"))
