# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 439)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 300))
        MainWindow.setMaximumSize(QtCore.QSize(800, 800))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout_11, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbxApprovalSert = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxApprovalSert.setObjectName("cbxApprovalSert")
        self.horizontalLayout_5.addWidget(self.cbxApprovalSert)
        self.lbTemplateApprovalCert = QtWidgets.QLabel(self.centralwidget)
        self.lbTemplateApprovalCert.setObjectName("lbTemplateApprovalCert")
        self.horizontalLayout_5.addWidget(self.lbTemplateApprovalCert)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.btTemplateApprovalCert = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btTemplateApprovalCert.sizePolicy().hasHeightForWidth())
        self.btTemplateApprovalCert.setSizePolicy(sizePolicy)
        self.btTemplateApprovalCert.setMinimumSize(QtCore.QSize(30, 0))
        self.btTemplateApprovalCert.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btTemplateApprovalCert.setObjectName("btTemplateApprovalCert")
        self.horizontalLayout_5.addWidget(self.btTemplateApprovalCert)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbxApprovalProtocol = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxApprovalProtocol.setObjectName("cbxApprovalProtocol")
        self.horizontalLayout_3.addWidget(self.cbxApprovalProtocol)
        self.lbTemplateApprovalProtocol = QtWidgets.QLabel(self.centralwidget)
        self.lbTemplateApprovalProtocol.setObjectName("lbTemplateApprovalProtocol")
        self.horizontalLayout_3.addWidget(self.lbTemplateApprovalProtocol)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btTemplateApprovalProtocol = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btTemplateApprovalProtocol.sizePolicy().hasHeightForWidth())
        self.btTemplateApprovalProtocol.setSizePolicy(sizePolicy)
        self.btTemplateApprovalProtocol.setMinimumSize(QtCore.QSize(30, 0))
        self.btTemplateApprovalProtocol.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btTemplateApprovalProtocol.setObjectName("btTemplateApprovalProtocol")
        self.horizontalLayout_3.addWidget(self.btTemplateApprovalProtocol)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lbScanFolder = QtWidgets.QLabel(self.centralwidget)
        self.lbScanFolder.setObjectName("lbScanFolder")
        self.horizontalLayout.addWidget(self.lbScanFolder)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btScanFolder = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btScanFolder.sizePolicy().hasHeightForWidth())
        self.btScanFolder.setSizePolicy(sizePolicy)
        self.btScanFolder.setMinimumSize(QtCore.QSize(30, 0))
        self.btScanFolder.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btScanFolder.setObjectName("btScanFolder")
        self.horizontalLayout.addWidget(self.btScanFolder)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lbDestFolder = QtWidgets.QLabel(self.centralwidget)
        self.lbDestFolder.setObjectName("lbDestFolder")
        self.horizontalLayout_2.addWidget(self.lbDestFolder)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btDestFolder = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btDestFolder.sizePolicy().hasHeightForWidth())
        self.btDestFolder.setSizePolicy(sizePolicy)
        self.btDestFolder.setMinimumSize(QtCore.QSize(30, 0))
        self.btDestFolder.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btDestFolder.setObjectName("btDestFolder")
        self.horizontalLayout_2.addWidget(self.btDestFolder)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cbxCalSert = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxCalSert.setObjectName("cbxCalSert")
        self.horizontalLayout_9.addWidget(self.cbxCalSert)
        self.lbTemplateCalCert = QtWidgets.QLabel(self.centralwidget)
        self.lbTemplateCalCert.setObjectName("lbTemplateCalCert")
        self.horizontalLayout_9.addWidget(self.lbTemplateCalCert)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.btTemplateCalCert = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btTemplateCalCert.sizePolicy().hasHeightForWidth())
        self.btTemplateCalCert.setSizePolicy(sizePolicy)
        self.btTemplateCalCert.setMinimumSize(QtCore.QSize(30, 0))
        self.btTemplateCalCert.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btTemplateCalCert.setObjectName("btTemplateCalCert")
        self.horizontalLayout_9.addWidget(self.btTemplateCalCert)
        self.gridLayout.addLayout(self.horizontalLayout_9, 8, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cbxCalProtocol = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxCalProtocol.setObjectName("cbxCalProtocol")
        self.horizontalLayout_8.addWidget(self.cbxCalProtocol)
        self.lbTemplateCalProtocol = QtWidgets.QLabel(self.centralwidget)
        self.lbTemplateCalProtocol.setObjectName("lbTemplateCalProtocol")
        self.horizontalLayout_8.addWidget(self.lbTemplateCalProtocol)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.btTemplateCalProtocol = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btTemplateCalProtocol.sizePolicy().hasHeightForWidth())
        self.btTemplateCalProtocol.setSizePolicy(sizePolicy)
        self.btTemplateCalProtocol.setMinimumSize(QtCore.QSize(30, 0))
        self.btTemplateCalProtocol.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btTemplateCalProtocol.setObjectName("btTemplateCalProtocol")
        self.horizontalLayout_8.addWidget(self.btTemplateCalProtocol)
        self.gridLayout.addLayout(self.horizontalLayout_8, 7, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cbxError = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxError.setObjectName("cbxError")
        self.horizontalLayout_7.addWidget(self.cbxError)
        self.lbTemplateError = QtWidgets.QLabel(self.centralwidget)
        self.lbTemplateError.setObjectName("lbTemplateError")
        self.horizontalLayout_7.addWidget(self.lbTemplateError)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.btTemplateError = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btTemplateError.sizePolicy().hasHeightForWidth())
        self.btTemplateError.setSizePolicy(sizePolicy)
        self.btTemplateError.setMinimumSize(QtCore.QSize(30, 0))
        self.btTemplateError.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btTemplateError.setObjectName("btTemplateError")
        self.horizontalLayout_7.addWidget(self.btTemplateError)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout.addLayout(self.horizontalLayout_10, 9, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_12.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.edApprovalProtocolNum = QtWidgets.QLineEdit(self.centralwidget)
        self.edApprovalProtocolNum.setObjectName("edApprovalProtocolNum")
        self.gridLayout.addWidget(self.edApprovalProtocolNum, 4, 1, 1, 1)
        self.edApprovalCertNum = QtWidgets.QLineEdit(self.centralwidget)
        self.edApprovalCertNum.setObjectName("edApprovalCertNum")
        self.gridLayout.addWidget(self.edApprovalCertNum, 5, 1, 1, 1)
        self.edErrorNum = QtWidgets.QLineEdit(self.centralwidget)
        self.edErrorNum.setObjectName("edErrorNum")
        self.gridLayout.addWidget(self.edErrorNum, 6, 1, 1, 1)
        self.edCalProtocolNum = QtWidgets.QLineEdit(self.centralwidget)
        self.edCalProtocolNum.setObjectName("edCalProtocolNum")
        self.gridLayout.addWidget(self.edCalProtocolNum, 7, 1, 1, 1)
        self.edCalCertNum = QtWidgets.QLineEdit(self.centralwidget)
        self.edCalCertNum.setObjectName("edCalCertNum")
        self.gridLayout.addWidget(self.edCalCertNum, 8, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 2, 1, 1, 1)
        self.edTemplateReserved = QtWidgets.QLineEdit(self.centralwidget)
        self.edTemplateReserved.setEnabled(True)
        self.edTemplateReserved.setObjectName("edTemplateReserved")
        self.gridLayout.addWidget(self.edTemplateReserved, 9, 1, 1, 1)
        self.btSaveSettings = QtWidgets.QPushButton(self.centralwidget)
        self.btSaveSettings.setObjectName("btSaveSettings")
        self.gridLayout.addWidget(self.btSaveSettings, 0, 1, 1, 1)
        self.gridLayout.setRowMinimumHeight(0, 6)
        self.gridLayout.setRowMinimumHeight(1, 6)
        self.gridLayout.setRowMinimumHeight(2, 6)
        self.gridLayout.setRowMinimumHeight(3, 6)
        self.gridLayout.setRowMinimumHeight(4, 6)
        self.gridLayout.setRowMinimumHeight(5, 6)
        self.gridLayout.setRowMinimumHeight(6, 6)
        self.gridLayout.setRowMinimumHeight(7, 6)
        self.gridLayout.setRowMinimumHeight(8, 6)
        self.gridLayout.setRowMinimumHeight(9, 6)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.chbAutoOpen = QtWidgets.QCheckBox(self.centralwidget)
        self.chbAutoOpen.setObjectName("chbAutoOpen")
        self.verticalLayout.addWidget(self.chbAutoOpen)
        self.chbAutoDelXML = QtWidgets.QCheckBox(self.centralwidget)
        self.chbAutoDelXML.setObjectName("chbAutoDelXML")
        self.verticalLayout.addWidget(self.chbAutoDelXML)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.exitAction = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitAction.setIcon(icon1)
        self.exitAction.setObjectName("exitAction")
        self.startAction = QtWidgets.QAction(MainWindow)
        self.startAction.setCheckable(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/player_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startAction.setIcon(icon2)
        self.startAction.setObjectName("startAction")
        self.stopAction = QtWidgets.QAction(MainWindow)
        self.stopAction.setCheckable(False)
        self.stopAction.setEnabled(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/player_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopAction.setIcon(icon3)
        self.stopAction.setVisible(True)
        self.stopAction.setIconVisibleInMenu(False)
        self.stopAction.setObjectName("stopAction")
        self.toolBar.addAction(self.exitAction)
        self.toolBar.addAction(self.startAction)
        self.toolBar.addAction(self.stopAction)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Шаблоны документов:"))
        self.cbxApprovalSert.setText(_translate("MainWindow", "Свидетельство о поверке"))
        self.lbTemplateApprovalCert.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btTemplateApprovalCert.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateApprovalCert.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateApprovalCert.setText(_translate("MainWindow", "..."))
        self.cbxApprovalProtocol.setText(_translate("MainWindow", "Протокол поверки"))
        self.lbTemplateApprovalProtocol.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btTemplateApprovalProtocol.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateApprovalProtocol.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateApprovalProtocol.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Папка XML:"))
        self.lbScanFolder.setText(_translate("MainWindow", "C:\\MCLinkReport\\XML"))
        self.btScanFolder.setToolTip(_translate("MainWindow", "Кнопка изменения папки XML"))
        self.btScanFolder.setStatusTip(_translate("MainWindow", "Кнопка изменения папки XML"))
        self.btScanFolder.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Папка Excel:"))
        self.lbDestFolder.setText(_translate("MainWindow", "C:\\MCLinkReport\\Excel"))
        self.btDestFolder.setToolTip(_translate("MainWindow", "Кнопка изменения папки Excel"))
        self.btDestFolder.setStatusTip(_translate("MainWindow", "Кнопка изменения папки Excel"))
        self.btDestFolder.setText(_translate("MainWindow", "..."))
        self.cbxCalSert.setText(_translate("MainWindow", "Сертификат калибровки"))
        self.lbTemplateCalCert.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btTemplateCalCert.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateCalCert.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateCalCert.setText(_translate("MainWindow", "..."))
        self.cbxCalProtocol.setText(_translate("MainWindow", "Протокол калибровки"))
        self.lbTemplateCalProtocol.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btTemplateCalProtocol.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateCalProtocol.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateCalProtocol.setText(_translate("MainWindow", "..."))
        self.cbxError.setText(_translate("MainWindow", "Извещение о непригодности"))
        self.lbTemplateError.setText(_translate("MainWindow", "C:\\MCLinkReport\\шаблон.xls"))
        self.btTemplateError.setToolTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateError.setStatusTip(_translate("MainWindow", "Кнопка изменения шаблона"))
        self.btTemplateError.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Пути:"))
        self.label_10.setText(_translate("MainWindow", "Номера документов:"))
        self.btSaveSettings.setText(_translate("MainWindow", "Сохранить настройки"))
        self.chbAutoOpen.setToolTip(_translate("MainWindow", "Автооткрытие протокола"))
        self.chbAutoOpen.setStatusTip(_translate("MainWindow", "Автооткрытие протокола"))
        self.chbAutoOpen.setText(_translate("MainWindow", "Автоматическое открытие протоколов"))
        self.chbAutoDelXML.setText(_translate("MainWindow", "Автоудаление XML"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.exitAction.setText(_translate("MainWindow", "Выход"))
        self.exitAction.setStatusTip(_translate("MainWindow", "Выход"))
        self.startAction.setText(_translate("MainWindow", "Запуск автосохранения"))
        self.startAction.setStatusTip(_translate("MainWindow", "Запуск автосохранения"))
        self.stopAction.setText(_translate("MainWindow", "Остановка автосохранения"))
        self.stopAction.setStatusTip(_translate("MainWindow", "Остановка автосохранения"))

